# Generated by Django 5.0.6 on 2024-07-08 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='uodated_at',
        ),
    ]
